import React from "react";

const Instructions = () => {
  return (
    <div className="flex flex-col md:flex-row items-start p-6 bg-gray-50 border border-gray-200 rounded-lg shadow-lg max-w-4xl mx-auto">
      <div className="flex-shrink-0 mb-4 md:mb-0 md:mr-6 flex items-center justify-center w-16 h-16 bg-gray-200 rounded-full">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          className="w-8 h-8 text-gray-600"
          viewBox="0 0 24 24"
          fill="none"
        >
          <path d="M0,0h24v24H0V0z" fill="none"></path>
          <path d="M14,2H6C4.9,2,4.01,2.9,4.01,4L4,20c0,1.1,0.89,2,1.99,2H18c1.1,0,2-0.9,2-2V8L14,2z M18,20H6V4h7v5h5V20z M8.82,13.05 L7.4,14.46L10.94,18l5.66-5.66l-1.41-1.41l-4.24,4.24L8.82,13.05z"></path>
        </svg>
      </div>
      <div className="flex-1">
        <h2 className="text-2xl md:text-3xl font-semibold mb-4">
          How to use the Document Summarizer online tool?
        </h2>
        <ol className="list-decimal list-inside space-y-2 text-gray-700">
          <li>Upload your document using the document summarizer tool.</li>
          <li>Preview the summary generated by the tool.</li>
          <li>Adjust the summary length or details if needed.</li>
        </ol>
      </div>
    </div>
  );
};

export default Instructions;
