import React from "react";

const Instructions = () => {
  return (
    <div className="flex flex-col md:flex-row items-start p-6 bg-gray-50 border border-gray-200 rounded-lg shadow-lg max-w-4xl mx-auto">
      <div className="flex-shrink-0 mb-4 md:mb-0 md:mr-6 flex items-center justify-center w-16 h-16 bg-gray-200 rounded-full">
      <h1 className="text-6xl font-bold text-black  p-4 rounded-full ">
        ?
      </h1>
      </div>
      <div className="flex-1">
        <h2 className="text-2xl md:text-3xl font-semibold mb-4">
          How to use the Document Summarizer online tool?
        </h2>
        <ol className="list-decimal list-inside space-y-2 text-gray-700">
          <li>Upload your document using the document summarizer tool.</li>
          <li>Preview the summary generated by the tool.</li>
          <li>Adjust the summary length or details if needed.</li>
        </ol>
      </div>
    </div>
  );
};

export default Instructions;
